#---- Configuration files ----
conda_config: "workflow/envs/conda.yaml"

#---- Directory structure config ----
reference: "data_input/reference"
samples_dir: "data_input/samples"
data_output_dir: "data_output"
log_dir: "logs"
cluster_log_dir: "cluster_logs"
benchmark_dir: "benchmarks"
filtered_read_dir: "reads/filtered"
alignment_dir: "data_output/alignment"


#---- Tool threads ----
trimmomatic_threads: 8
bowtie2_threads: 8
sort_threads: 5
fixmate_threads: 4
markdup_threads: 4
bamutil_clipoverlap_threads: 4

#---- Tool memory ----
trimmomatic_mem_mb: 16000
bowtie2_mem_mb: 30000
per_thread_sort_mem: 10 # memory in gigabytes
fixmate_mem_mb: 10000
markdup_mem_mb: 10000
bamutil_clipoverlap_mem_mb: 15000

#---- Tool time ----
trimmomatic_time: "100:00:00"
bowtie2_time: "100:00:00"
bamutil_clipoverlap_time: "100:00:00"

#---- Tool paths ----


#---- Tool variables ----
adapters: "resources/adapters/TruSeq2-PE.fa"
poolsize: 10000000



