#---- Configuration files ----
conda_config: "workflow/envs/conda.yaml"

#---- Directory structure config ----
reference: "input_data/reference"
samples_dir: "input_data/samples"
output_dir: "results"
log_dir: "logs"
cluster_log_dir: "cluster_logs"
benchmark_dir: "benchmarks"
filtered_read_dir: "reads/filtered"
raw_alignment_dir: "alignment/raw"
clipped_alignment_dir: "alignment/clipped"
raw_coverage_dir: "coverage"
clipped_coverage_dir: "coverage"

#---- Tool threads ----
trimmomatic_threads: 8
bowtie2_threads: 8
sort_threads: 5
fixmate_threads: 4
markdup_threads: 4
bamutil_clipoverlap_threads: 4
mosdepth_threads: 4
index_threads: 4

#---- Tool memory ----
trimmomatic_mem_mb: 16000
bowtie2_mem_mb: 30000
per_thread_sort_mem: 10 # memory in gigabytes
fixmate_mem_mb: 10000
markdup_mem_mb: 10000
bamutil_clipoverlap_mem_mb: 15000
mosdepth_mem_mb: 20000
index_mem_mb: 10000

#---- Tool time ----
trimmomatic_time: "100:00:00"
bowtie2_time: "100:00:00"
bamutil_clipoverlap_time: "100:00:00"
mosdepth_time: "100:00:00"
index_time: "50:00:00"

#---- Tool paths ----


#---- Tool variables ----
adapters: "resources/adapters/TruSeq2-PE.fa"
poolsize: 10000000
mosdepth_min_mapping_quality: 20



