#---- Bioconda config ----
name: ITSpipe
channels:
  - bioconda
  - conda-forge
dependencies:
  - python>=3.8
  - trimmomatic>=0.39
  - bowtie2>=2.4.4
  - samtools>=1.10
  - bcftools>=1.12
  - bamutil>=1.0.15
  - mosdepth>=0.3.1
  - gatk4=4.2.0.0
  - picard=2.18
  - pisces==5.3
  - dotnet==2.1.818
  - numpy>=1.10
  - pandas>=1.2
  - matplotlib